### PR TITLE
Rough attempt at exclude config option

### LINKED ISSUE #76: Feature request: sortier.onSave by language
It would be nice to be able to configure which languages apply sortier.onSave e.g.
```
{
  "[javascript]": {
    "editor.formatOnSave": true,
    "sortier.onSave": true
  },
  "[javascriptreact]": {
    "editor.formatOnSave": true,
    "sortier.onSave": true
  }
}
```

### PR DESCRIPTION
**Pull request by TikiTDO**
Tries to fix #76 and #77

### CODE REVIEW

**Comment by TikiTDO** [comment]
I've added both include and exclude functionality. Let me know if this meets your needs, and if there's any other changes necessary.

**Comment by k2snowman69** [comment]
This is awesome! And a fantastic start! A few notes:
 - Feel free to create a branch on this repository, makes it easier to collaborate
 - Seems that the code itself doesn't actually compile
 - I don't think you need both excludes and includes only includes. Glob's allow for `!` which negates thus becoming an excludes.

I created `k2snowman69/includesProperty` which fixes most of these issues but I find that minimatch on windows is resulting in false in odd situations. For example:
```
includeCandidate
"*.js"
fileName
"d:\Projects\react-ui-base\dialog\.lintstagedrc.js"
matcher.match(fileName)
false
matcher.match("d:\Projects\react-ui-base\dialog\.lintstagedrc.js")
true
```

**Comment by TikiTDO** [comment]
Looks like that example didn't come through in full.

If I were to guess the reason for the difference then most likely the string getting passed in the last call to match is treating the backslashes as escape chars.

image

I think in that case it treats the entire thing as a file named `d:Projects
eact-ui-basedialog.lintstagedrc.js` as above. By contrast when you have the full path in the variable it will probably refuse to match that because it might be expecting to match the full path. 

You can try playing with the `matchBase` option, or setting the pattern to `**/*.js`

**Comment by k2snowman69** [comment]
If that were the case then simply exchanging out all the `\` with `/` would resolve the issue but it doesn't. I think something else is going on here...

**Comment by TikiTDO** [comment]
Closing in favor of #116

**Comment by TikiTDO** [comment]
My understanding is that anything with valid slashes, be it `\` or `/` should return a `false` for the pattern `*.js`. If that's not the case then I'd need to play with it myself to see what's going on. However, I just spend most of the week killing every trace of windows that I still had on my machine, so I'm not in a position to test this easily. 

You mentioned `ignore` works, so I figure that's good enough.

**Pull request closed without merging**
